package bridge

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"

	"github.com/BurntSushi/toml"
)

type InitReport struct {
	ManifestPath string `json:"manifest_path"`
	ProfilePath  string `json:"profile_path"`
	Endpoint     string `json:"endpoint"`
	CatalogPath  string `json:"catalog_path"`
	Action       string `json:"action"`
	Backup       string `json:"backup,omitempty"`
}

// RefreshHostManifest only replaces manifests generated by this tool. The
// previous file is backed up before replacement; unrelated manifests remain
// untouched.
func RefreshHostManifest(target string) (InitReport, error) {
	target = expandPath(target)
	previous, err := os.ReadFile(target)
	if err != nil {
		return InitReport{}, err
	}
	if !bytes.HasPrefix(previous, []byte("# Suggested bridge.toml\n")) {
		return InitReport{}, errors.New("refusing to refresh a manifest not generated by bridge init")
	}
	m, source, err := discoverHostManifest()
	if err != nil {
		return InitReport{}, err
	}
	var content bytes.Buffer
	if err := PrintAdopt(&content, m); err != nil {
		return InitReport{}, err
	}
	backup := fmt.Sprintf("%s.bak.%d", target, time.Now().UnixNano())
	if err := copyFile(target, backup); err != nil {
		return InitReport{}, err
	}
	if err := atomicWrite(target, content.Bytes(), 0o600); err != nil {
		return InitReport{}, err
	}
	return InitReport{ManifestPath: target, ProfilePath: source, Endpoint: m.Profiles.CPA.Endpoint, CatalogPath: m.Profiles.CPA.ModelCatalogJSON, Action: "refreshed", Backup: backup}, nil
}

// InitManifestFromHost discovers an existing CPA-backed Codex profile and
// writes only a new bridge manifest. It never rewrites the discovered profile.
func InitManifestFromHost(target string, write bool) (InitReport, error) {
	target = expandPath(target)
	if info, err := os.Lstat(target); err == nil {
		return InitReport{}, fmt.Errorf("manifest already exists at %s (%s); select another path", target, info.Mode())
	} else if !errors.Is(err, os.ErrNotExist) {
		return InitReport{}, err
	}
	m, source, err := discoverHostManifest()
	if err != nil {
		return InitReport{}, err
	}
	report := InitReport{ManifestPath: target, ProfilePath: source, Endpoint: m.Profiles.CPA.Endpoint, CatalogPath: m.Profiles.CPA.ModelCatalogJSON, Action: "preview"}
	if !write {
		return report, nil
	}
	var content bytes.Buffer
	if err := PrintAdopt(&content, m); err != nil {
		return InitReport{}, err
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o700); err != nil {
		return InitReport{}, err
	}
	if err := atomicWrite(target, content.Bytes(), 0o600); err != nil {
		return InitReport{}, err
	}
	report.Action = "created"
	return report, nil
}

func discoverHostManifest() (Manifest, string, error) {
	m := DefaultManifest()
	home, err := os.UserHomeDir()
	if err != nil {
		return Manifest{}, "", err
	}
	candidates := []string{os.Getenv("CODEX_HOME"), filepath.Join(home, ".codex-mac-cpa"), filepath.Join(home, ".codex-cpa")}
	if runtime.GOOS == "linux" {
		// Headless hosts often use their normal Codex home as the CPA profile.
		candidates = append(candidates, m.Profiles.Official.Home)
	}
	seen := map[string]bool{}
	for _, candidate := range candidates {
		if candidate == "" {
			continue
		}
		candidate = expandPath(candidate)
		if seen[candidate] || runtime.GOOS != "linux" && filepath.Clean(candidate) == filepath.Clean(m.Profiles.Official.Home) {
			continue
		}
		seen[candidate] = true
		path := filepath.Join(candidate, "config.toml")
		var config struct {
			Model            string `toml:"model"`
			ModelProvider    string `toml:"model_provider"`
			ModelCatalogJSON string `toml:"model_catalog_json"`
			ModelProviders   map[string]struct {
				BaseURL string `toml:"base_url"`
				EnvKey  string `toml:"env_key"`
				Auth    struct {
					Command string   `toml:"command"`
					Args    []string `toml:"args"`
				} `toml:"auth"`
			} `toml:"model_providers"`
		}
		if _, err := toml.DecodeFile(path, &config); err != nil {
			continue
		}
		provider, ok := config.ModelProviders[config.ModelProvider]
		providerName := strings.ToLower(config.ModelProvider)
		if !ok || !strings.Contains(providerName, "cpa") && !strings.Contains(providerName, "cliproxy") || !strings.HasPrefix(provider.BaseURL, "http://") && !strings.HasPrefix(provider.BaseURL, "https://") {
			continue
		}
		catalogPath := ""
		if config.ModelCatalogJSON != "" {
			catalogPath = expandPath(config.ModelCatalogJSON)
			if !filepath.IsAbs(config.ModelCatalogJSON) {
				catalogPath = filepath.Join(candidate, config.ModelCatalogJSON)
			}
		}
		if _, err := os.Stat(catalogPath); err != nil && runtime.GOOS == "linux" && candidate != m.Profiles.Official.Home {
			catalogPath = sharedOfficialCatalog(m.Profiles.Official.Home, provider.BaseURL)
		}
		if catalogPath == "" {
			continue
		}
		if _, err := os.Stat(catalogPath); err != nil {
			continue
		}
		if pathIsManaged(path) {
			m.Profiles.CPA.Management = "managed"
		} else {
			m.Profiles.CPA.Management = "external"
		}
		m.Profiles.CPA.Home = candidate
		m.Profiles.CPA.Endpoint = strings.TrimRight(provider.BaseURL, "/")
		if config.Model != "" {
			m.Profiles.CPA.Model = config.Model
		}
		m.Profiles.CPA.ProviderName = config.ModelProvider
		m.Profiles.CPA.ModelCatalogJSON = catalogPath
		m.Profiles.CPA.EnvKey = provider.EnvKey
		// Only copy known-safe helper forms. Arbitrary arguments may contain
		// inline secrets and must not be persisted into the manifest.
		if provider.Auth.Command != "" && filepath.IsAbs(provider.Auth.Command) {
			if len(provider.Auth.Args) == 0 {
				m.Profiles.CPA.AuthCommand = provider.Auth.Command
			} else if filepath.Base(provider.Auth.Command) == "security" && len(provider.Auth.Args) >= 2 && provider.Auth.Args[0] == "find-generic-password" && provider.Auth.Args[len(provider.Auth.Args)-1] == "-w" {
				m.Profiles.CPA.AuthCommand = provider.Auth.Command
				m.Profiles.CPA.AuthArgs = provider.Auth.Args
			}
		}
		if runtime.GOOS == "linux" {
			_, officialBaseURL := activeProviderBaseURL(filepath.Join(m.Profiles.Official.Home, "config.toml"))
			if sameEndpoint(officialBaseURL, m.Profiles.CPA.Endpoint) {
				m.Profiles.Official.EnforceNativeLogin = false
			}
		}
		if err := m.validate(); err != nil {
			continue
		}
		discoverLocalSSH(&m)
		return m, path, nil
	}
	return Manifest{}, "", errors.New("no CPA-backed Codex profile with a model catalog was found; configure a profile first or provide a manifest manually")
}

func sharedOfficialCatalog(home, endpoint string) string {
	path := filepath.Join(home, "config.toml")
	var official struct {
		ModelCatalogJSON string `toml:"model_catalog_json"`
	}
	if _, err := toml.DecodeFile(path, &official); err != nil || official.ModelCatalogJSON == "" {
		return ""
	}
	_, baseURL := activeProviderBaseURL(path)
	if !sameEndpoint(baseURL, endpoint) {
		return ""
	}
	catalog := official.ModelCatalogJSON
	if !filepath.IsAbs(catalog) {
		catalog = filepath.Join(home, catalog)
	}
	return expandPath(catalog)
}

func discoverLocalSSH(m *Manifest) {
	path := filepath.Join(m.Runtime.StateDir, "ssh", "sshd_config")
	raw, err := os.ReadFile(path)
	if err != nil {
		return
	}
	port := 0
	host := ""
	for _, line := range strings.Split(string(raw), "\n") {
		fields := strings.Fields(line)
		if len(fields) < 2 || strings.HasPrefix(fields[0], "#") {
			continue
		}
		switch strings.ToLower(fields[0]) {
		case "port":
			if value, err := strconv.Atoi(fields[1]); err == nil && value > 0 && value < 65536 {
				port = value
			}
		case "listenaddress":
			if fields[1] == "127.0.0.1" || fields[1] == "::1" {
				host = fields[1]
			}
		}
	}
	if port == 0 || host == "" {
		return
	}
	if pathIsManaged(path) {
		m.SSH.CPA.Management = "managed"
	} else {
		m.SSH.CPA.Management = "external"
	}
	m.SSH.CPA.Host = host
	m.SSH.CPA.Port = port
	identity := expandPath("~/.ssh/id_ed25519")
	if info, err := os.Stat(identity); err == nil && info.Mode().IsRegular() {
		m.SSH.CPA.IdentityFile = identity
	} else {
		identity = filepath.Join(m.Runtime.StateDir, "ssh", "bridge_client_ed25519")
		if info, err := os.Stat(identity); err == nil && info.Mode().IsRegular() {
			m.SSH.CPA.IdentityFile = identity
		}
	}
}
